### ISSUE TITLE
KeyError: 'softmax_label'

### ISSUE THREAD

**Issue by BebDong** [Ldpe2G/DeepLearningForFun#5]
请问出现这个问题是什么原因呢
`D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\base_module.py:67: UserWarning: Data provided by label_shapes don't match names specified by label_names ([DataDesc[softmax_label,(1, 21, 384, 384),<class 'numpy.float32'>,NCHW]] vs. [])
  warnings.warn(msg)
Traceback (most recent call last):
  File "calculateFlops.py", line 64, in <module>
    model.bind(data_shapes=data_shapes, label_shapes=label_shapes, for_training=False)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 382, in bind_exec
    self._collect_arrays()
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 319, in _collect_arrays
    for name, _ in self.label_shapes]
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 319, in <listcomp>
    for name, _ in self.label_shapes]
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 318, in <listcomp>
    for i, e in enumerate(self.execs)]
KeyError: 'softmax_label'`

**Comment by BebDong** [comment]
D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\base_module.py:67: UserWarning: Data provided by label_shapes don't match names specified by label_names ([DataDesc[softmax_label,(1, 21, 384, 384),<class 'numpy.float32'>,NCHW]] vs. [])
  warnings.warn(msg)
Traceback (most recent call last):
  File "calculateFlops.py", line 64, in <module>
    model.bind(data_shapes=data_shapes, label_shapes=label_shapes, for_training=False)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 382, in bind_exec
    self._collect_arrays()
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 319, in _collect_arrays
    for name, _ in self.label_shapes]
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 319, in <listcomp>
    for name, _ in self.label_shapes]
  File "D:\Anaconda3\envs\mxnet\lib\site-packages\mxnet\module\executor_group.py", line 318, in <listcomp>
    for i, e in enumerate(self.execs)]
KeyError: 'softmax_label'

**Comment by Ldpe2G** [comment]
你的symbol里面有softmax_label这个节点吗，你可以对比看下symbols目录下的json。

**Comment by BebDong** [comment]
@Ldpe2G 感谢回复！参考了你给的symbols目录下的.json文件，大概明白是什么原因了。我是直接使用HybridBlock的export方法生成的.json，好像和直接使用Symbol定义网络生成的.json不太一样。我的HybridBlock模型定义的hybrid_forward里面是没有使用Softmax的，这一步放在损失函数定义里面了，所以没有softmax_label这个节点。请问这种情况要怎么处理呢？（我是使用的ResNet FCN32s，最后的一个节点是双线性差值上采样）

**Comment by Ldpe2G** [comment]
如果没有softmax的话，调用 calculateFlops.py 这个脚本的时候不需要传ls这个参数，只需要ds就行了，或者你提供下 json 文件我帮你看下，直接发到我邮箱就行了。

**Comment by BebDong** [comment]
@Ldpe2G 不使用ls参数报错：
Traceback (most recent call last):
  File "calculateFlops.py", line 105, in <module>
    total_flops += out_shape_produt * product(arg_params[layer_name + '_weight'].shape) * data_shapes[0][1][0]
KeyError: 'resnetv1b_conv0_fwd_weight'

所使用的.json文件已发你邮箱，谢谢！

**Comment by Ldpe2G** [comment]
我把json文件改了下，我这边测试没问题了，你试下，文件发你邮箱了

**Comment by BebDong** [comment]
@Ldpe2G 非常感谢！
